package com.x3platform.util;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.time.LocalDateTime;

import static org.junit.Assert.*;

public class DateUtilTests {
  @Test
  public void testGetDefaultTime() {
    LocalDateTime date = DateUtil.getDefaultTime();

    assertEquals("DateUtil.getDefaultTime() should return 1970-01-01T00:00", "1970-01-01T00:00", date.toString());
  }

  @Test
  public void testGetTimestamp() {
    LocalDateTime now = LocalDateTime.now();

    long timestamp = DateUtil.getTimestamp();

    long timestamp2 = DateUtil.getTimestamp(now);

    assertEquals("DateUtil.getDefaultTime() should return 1970-01-01T00:00", "1970-01-01T00:00", timestamp);
  }

  @Test
  public void testToLocalDateTime() {
    LocalDateTime datetime = DateUtil.toLocalDateTime(1527407368L);

    // assertEquals("DateUtil.getDefaultTime() should return 1970-01-01T00:00", "1970-01-01T00:00", datetime);
  }
}
