package com.x3platform.util;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class StringUtilTests {
  // 测试随机字符串
  @Test
  public void testToRandom() {
    String randomText1 = StringUtil.toRandom(8);
    String randomText2 = StringUtil.toRandom(8);

    assertEquals("randomText1.length() should return 8", 8, randomText1.length());
    assertEquals("randomText2.length() should return 8", 8, randomText2.length());
    assertFalse("randomText1.equals(randomText2) should return 'false'", randomText1.equals(randomText2));
  }

  @Test
  public void testToBase64() {
    String result = StringUtil.toBase64("abc");
    assertTrue("StringHelper.toBase64 should return 'true'", result.length() > 0);
  }
}
