language: java
os:
  - linux
install:
  - echo install ok.
script:
  - mvn clean resources:resources install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - echo after_success ok.
