language: java
os:
  - linux
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn resources:resources
  - mvn resources:testResources
script:
  - mvn test -B
after_success:
  - echo ok
