language: java
os:
  - linux
services:
  - mysql
  - redis-server
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS x3_base; ALTER DATABASE x3_base CHARACTER SET utf8;'
install:
  - echo install ok.
before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -uroot -proot x3_base < database/scripts/install-script-latest-mysql.sql
script:
  - mvn clean resources:resources install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - echo after_success ok.
