package com.x3platform.util;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ValidationHelperTest {
    @Test public void testToBase64() {
        boolean result = ValidationHelper.isNull("abc");
        assertTrue("StringHelper.toBase64 should return 'true'", result);
    }
}
