package com.x3platform.membership;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ConnectContext {
  public boolean someLibraryMethod() {
    return true;
  }
}
